### ISSUE TITLE
Shared IPC connect failed after multiple attempts (308)

### ISSUE THREAD

**Issue by thegergo02** [ChristophHaag/SteamVR-OpenHMD#11]
After I start the docker script, the steamVR tells me this, then I try to run a game, and I get the same exact message. (I just want to see the game in the composition view, I don't know if I need the headset connected or not.)

**Comment by thegergo02** [comment]
The room setup displays everything in the composition view, so I don't think I need a headset connected.

**Comment by thegergo02** [comment]
I think I need to test this with my main machine, I just don't have it here, so I close the issue.

**Comment by buzztiaan** [comment]
did you ever find the root cause of this?
