### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by Holzhaus** [ChristophHaag/SteamVR-OpenHMD#18]
What license is this code under? OpenHMD is under Boost Software License 1.0. Does it apply to this repo as well?

**Comment by ChristophHaag** [comment]
Good question. I like GPLv3 but I'm not sure if this really works for SteamVR plugins and I guess people wouldn't like it much. Also I'm pretty sure someone already used it in a commercial proprietary project, so...

It's now the same license as OpenHMD.

**Comment by Holzhaus** [comment]
Nice, that was quick.
