### ISSUE TITLE
Displays SteamVR content to monitor and not headset

### ISSUE THREAD

**Issue by crparis1** [ChristophHaag/SteamVR-OpenHMD#27]
So I was able to install the module and get SteamVR up and running with OHMD.  The problem is that instead of sending the visuals to the headset, they are being sent to the monitor.  Moving the headset moves the images on the monitor, so it is tracking ok but it is not sending the output to the headset.

**Comment by crparis1** [comment]
I forgot the nvidia additions for xorg.conf.  Apologies!

**Comment by Doomsdayrs** [comment]
I'm having this issue,  but with an AMD gpu (rx 580)
