### ISSUE TITLE
no instructions on how to install for windows

### ISSUE THREAD

**Issue by herosilas12** [ChristophHaag/SteamVR-OpenHMD#38]
I managed to get it to build but when I run cmake_install.cmake it doesn't work

**Comment by herosilas12** [comment]
once I know where to put it I can write a batch or python script to install it properly automatically

**Comment by herosilas12** [comment]
nevermind

**Comment by thaytan** [comment]
@TheOnlyJoey was building the plugin on Windows yesterday - so hopefully some docs are incoming soon!

**Comment by herosilas12** [comment]
thanks for the update
can't wait to try it out :)

**Comment by herosilas12** [comment]
any updates on how building is going?

**Comment by TheOnlyJoey** [comment]
@herosilas12 Please don't spam the github issues, if something will happen you will see it.
