### ISSUE TITLE
Room Setup on the Rift S acting strange

### ISSUE THREAD

**Issue by actuallyexeon** [ChristophHaag/SteamVR-OpenHMD#63]
I am doing my room setup for steamvr (arch linux), and it seems the controllers are just all over the place. I think it's because they have no position tracking which really sucks, is there any way to fix this or get at least controller movement?

**Comment by thaytan** [comment]
The Rift S driver is only 3DOF so far - positional tracking for it is still a ways off.

**Comment by actuallyexeon** [comment]
oof guess ill just use windows for now
