### ISSUE TITLE
CV1 sensor not working?

### ISSUE THREAD

**Issue by Gregory-Hepicloud** [ChristophHaag/SteamVR-OpenHMD#66]
Hi we have install and run steamvr headset working remote dont working and if move in room not follow and my sensor on wall not start (no white led)

`Thu Jul 29 2021 22:26:05.602136 - //==============================================================================================
Thu Jul 29 2021 22:26:05.602178 - ================================================================================================
Thu Jul 29 2021 22:26:05.602189 - ================================================================================================
Thu Jul 29 2021 22:26:05.602203 - vrserver 1.18.7 startup with PID=16202, config=/home/greg/.steam/debian-installation/config, runtime=/home/greg/.steam/debian-installation/steamapps/common/SteamVR
Thu Jul 29 2021 22:26:05.602367 - CSharedResourceNamespaceServer starting up
Thu Jul 29 2021 22:26:05.602435 - CIPCPipe::ConnectPipe(SteamVR_Namespace) attempting connect to steamvr:SteamVR_Namespace
Thu Jul 29 2021 22:26:05.602475 - Unable to connect to pipe errno=111
Thu Jul 29 2021 22:26:05.602497 - CSharedResourceNamespaceClient::Init(): failed connect
Thu Jul 29 2021 22:26:05.602510 - CSharedResourceNamespaceClient::Init(): still waiting for vrserver to reply with namespace data
Thu Jul 29 2021 22:26:05.605569 - Failed to set thread priority: set failed for 5: -1: setpriority() failed
Thu Jul 29 2021 22:26:05.605610 - Failed to set thread priority: setschedparam failed 5: 1
Thu Jul 29 2021 22:26:05.605623 - Failed to set thread priority: invalid priority 5
Thu Jul 29 2021 22:26:05.605647 - CIPCPipe::CreatePipe(SteamVR_Namespace) bound to steamvr:SteamVR_Namespace
Thu Jul 29 2021 22:26:05.605733 - Set thread 0x7fa83dceb640 priority to: -15
Thu Jul 29 2021 22:26:05.702613 - CIPCPipe::ConnectPipe(SteamVR_Namespace) attempting connect to steamvr:SteamVR_Namespace
Thu Jul 29 2021 22:26:05.702722 - CSharedResourceNamespaceServer sent namespace data: 16202
Thu Jul 29 2021 22:26:05.702759 - CSharedResourceNamespaceClient::Init(): received namespace data 16202
Thu Jul 29 2021 22:26:05.702803 - Self queried namespace: 16202
Thu Jul 29 2021 22:26:05.703864 - VR server 1.18.7 (v1625702712) starting up with config=/home/greg/.steam/debian-installation/config
Thu Jul 29 2021 22:26:05.703887 - VRServer will wait for VRMonitor before exiting
Thu Jul 29 2021 22:26:05.703968 - CIPCPipe::CreatePipe(VR_ServerPipe_16202) bound to steamvr:VR_ServerPipe_16202
Thu Jul 29 2021 22:26:05.704617 - [Settings] Load Default Json Settings from /home/greg/.steam/debian-installation/steamapps/common/SteamVR/drivers/htc/resources/settings/default.vrsettings
Thu Jul 29 2021 22:26:05.704672 - [Settings] Load Default Json Settings from /home/greg/.steam/debian-installation/steamapps/common/SteamVR/drivers/lighthouse/resources/settings/default.vrsettings
Thu Jul 29 2021 22:26:05.704726 - [Settings] Load Default Json Settings from /home/greg/.steam/debian-installation/steamapps/common/SteamVR/drivers/null/resources/settings/default.vrsettings
Thu Jul 29 2021 22:26:05.704765 - [Settings] Load Default Json Settings from /home/greg/SteamVR-OpenHMD/build/resources/settings/default.vrsettings
Thu Jul 29 2021 22:26:05.704910 - [Settings] Load Default Json Settings from /home/greg/.steam/debian-installation/steamapps/common/SteamVR/resources/settings/default.vrsettings
Thu Jul 29 2021 22:26:05.705259 - [Settings] Load Json Settings from /home/greg/.steam/debian-installation/config/steamvr.vrsettings
Thu Jul 29 2021 22:26:05.714120 - [Settings] Load Default Json Settings from /home/greg/.steam/debian-installation/steamapps/common/SteamVR/drivers/htc/resources/settings/default.vrsettings
Thu Jul 29 2021 22:26:05.714177 - [Settings] Load Default Json Settings from /home/greg/.steam/debian-installation/steamapps/common/SteamVR/drivers/lighthouse/resources/settings/default.vrsettings
Thu Jul 29 2021 22:26:05.714221 - [Settings] Load Default Json Settings from /home/greg/SteamVR-OpenHMD/build/resources/settings/default.vrsettings
Thu Jul 29 2021 22:26:05.714259 - [Settings] Load Default Json Settings from /home/greg/.steam/debian-installation/steamapps/common/SteamVR/drivers/null/resources/settings/default.vrsettings
Thu Jul 29 2021 22:26:05.714413 - [Settings] Load Default Json Settings from /home/greg/.steam/debian-installation/steamapps/common/SteamVR/resources/settings/default.vrsettings
Thu Jul 29 2021 22:26:05.714774 - [Settings] Load Json Settings from /home/greg/.steam/debian-installation/config/steamvr.vrsettings
Thu Jul 29 2021 22:26:05.715248 - /home/greg/.steam/debian-installation/steamapps/common/SteamVR/tools/tools.vrmanifest - App openvr.tool.steamvr_media_player must specify binary_path for launch_type binary. Skipping
Thu Jul 29 2021 22:26:05.715282 - /home/greg/.steam/debian-installation/steamapps/common/SteamVR/tools/tools.vrmanifest - App openvr.tool.steamvr_desktop_gametheatre Working directory /home/greg/.steam/debian-installation/steamapps/common/SteamVR/tools/steamvr_desktop_game_theater/linux64 is invalid. Skipping. Skipping
Thu Jul 29 2021 22:26:05.715455 - CSharedResourceNamespaceServer sent namespace data: 16202
Thu Jul 29 2021 22:26:05.716711 - Adding controller type vive_controller
Thu Jul 29 2021 22:26:05.716998 - Adding controller type oculus_touch
Thu Jul 29 2021 22:26:05.717292 - Adding controller type knuckles
Thu Jul 29 2021 22:26:05.979257 - Add Json firmware manifest from {htc}/firmware/manifest.vrfirmware
Thu Jul 29 2021 22:26:05.979348 - Add Json firmware manifest from {indexcontroller}/firmware/manifest.vrfirmware
Thu Jul 29 2021 22:26:05.979416 - Add Json firmware manifest from {indexhmd}/firmware/manifest.vrfirmware
Thu Jul 29 2021 22:26:05.979502 - Web language is english
Thu Jul 29 2021 22:26:05.979575 - [Web] Starting web server on port 27062
Thu Jul 29 2021 22:26:05.980418 - Rejecting vrclient connection from /home/greg/.steam/debian-installation/steamapps/common/SteamVR/bin/linux64/vrstartup with client DLL "/home/greg/.steam/debian-installation/steamapps/common/SteamVR/bin/linux64/vrclient.so" (v1.18.7)
Thu Jul 29 2021 22:26:05.980746 - New Connect message from /home/greg/.steam/debian-installation/steamapps/common/SteamVR/bin/linux64/vrstartup (VRApplication_Bootstrapper) (Args: ) 16120 
Thu Jul 29 2021 22:26:05.980771 - Creating Builtin AppInfo for /home/greg/.steam/debian-installation/steamapps/common/SteamVR/bin/linux64/vrstartup (VRApplication_Bootstrapper). steam.overlay.250820, , 16120
Thu Jul 29 2021 22:26:05.980790 - AppInfoManager.ProcessConnected BEGIN 16120 /home/greg/.steam/debian-installation/steamapps/common/SteamVR/bin/linux64/vrstartup 7 steam.overlay.250820
Thu Jul 29 2021 22:26:05.980802 - SetApplicationPid appkey=steam.overlay.250820 pid=16120, external transition
Thu Jul 29 2021 22:26:05.980812 - SetApplicationPid: Setting app steam.overlay.250820 PID to 16120
Thu Jul 29 2021 22:26:05.980828 - AppInfoManager.ProcessConnected END
Thu Jul 29 2021 22:26:05.980983 - Enabling legacy input for steam.overlay.250820
Thu Jul 29 2021 22:26:05.982114 - Not loading driver lighthouse because it is disabled in settings
Thu Jul 29 2021 22:26:05.982133 - Not loading driver oculus because it is disabled in settings
Thu Jul 29 2021 22:26:05.982144 - Not loading driver oculus_legacy because it is disabled in settings
Thu Jul 29 2021 22:26:06.051219 - openhmd: could not open config file /home/greg/.ohmd_config.txt, using default headset 0 with no controller
Thu Jul 29 2021 22:26:06.051277 - openhmd: could not open config file /home/greg/.ohmd_config.txt, using default headset 0 with no controller
Thu Jul 29 2021 22:26:06.051290 - openhmd: could not open config file /home/greg/.ohmd_config.txt, using default headset 0 with no controller
Thu Jul 29 2021 22:26:06.051302 - openhmd: could not open config file /home/greg/.ohmd_config.txt, using default headset 0 with no controller
Thu Jul 29 2021 22:26:06.051313 - openhmd: device 0
Thu Jul 29 2021 22:26:06.051322 - openhmd:   vendor:  Oculus VR, Inc.
Thu Jul 29 2021 22:26:06.051331 - openhmd:   product: Rift (CV1)
Thu Jul 29 2021 22:26:06.051340 - openhmd:   path:    0003:0009:00

Thu Jul 29 2021 22:26:06.051349 - openhmd: device 1
Thu Jul 29 2021 22:26:06.051358 - openhmd:   vendor:  Oculus VR, Inc.
Thu Jul 29 2021 22:26:06.051367 - openhmd:   product: Rift (CV1): Right Controller
Thu Jul 29 2021 22:26:06.051376 - openhmd:   path:    0003:0009:00

Thu Jul 29 2021 22:26:06.051392 - openhmd: device 2
Thu Jul 29 2021 22:26:06.051401 - openhmd:   vendor:  Oculus VR, Inc.
Thu Jul 29 2021 22:26:06.051412 - openhmd:   product: Rift (CV1): Left Controller
Thu Jul 29 2021 22:26:06.051421 - openhmd:   path:    0003:0009:00

Thu Jul 29 2021 22:26:06.051430 - openhmd: device 3
Thu Jul 29 2021 22:26:06.051439 - openhmd:   vendor:  OpenHMD
Thu Jul 29 2021 22:26:06.051447 - openhmd:   product: External Device
Thu Jul 29 2021 22:26:06.051456 - openhmd:   path:    (none)

Thu Jul 29 2021 22:26:06.051464 - openhmd: device 4
Thu Jul 29 2021 22:26:06.051473 - openhmd:   vendor:  OpenHMD
Thu Jul 29 2021 22:26:06.051481 - openhmd:   product: HMD Null Device
Thu Jul 29 2021 22:26:06.051490 - openhmd:   path:    (none)

Thu Jul 29 2021 22:26:06.051499 - openhmd: device 5
Thu Jul 29 2021 22:26:06.051508 - openhmd:   vendor:  OpenHMD
Thu Jul 29 2021 22:26:06.051516 - openhmd:   product: Left Controller Null Device
Thu Jul 29 2021 22:26:06.051525 - openhmd:   path:    (none)

Thu Jul 29 2021 22:26:06.051533 - openhmd: device 6
Thu Jul 29 2021 22:26:06.051542 - openhmd:   vendor:  OpenHMD
Thu Jul 29 2021 22:26:06.051551 - openhmd:   product: Right Controller Null Device
Thu Jul 29 2021 22:26:06.051559 - openhmd:   path:    (none)

Thu Jul 29 2021 22:26:06.051568 - openhmd: Using HMD Display 0, HMD Tracker 0, Left Controller 2, Right Controller 1`

ps : if you need log or other who can found it?

thx

**Comment by thaytan** [comment]
The easiest option is to build the controller-haptics-wip branch of SteamVR-OpenHMD from my repo: https://github.com/thaytan/SteamVR-OpenHMD/tree/controller-haptics-wip

That will pull in the right OpenHMD branch. You also need to make sure you have USB rules to allow access to the sensor devices. https://github.com/OpenHMD/OpenHMD/wiki/Udev-rules-list has some info. The xr-hardware rules are the most complete.

**Comment by thaytan** [comment]
If you have any further trouble, let us know or jump on the #openhmd IRC channel on the Libera.chat IRC server
