### ISSUE TITLE
Is Quake2VR for Linux an open source project?

### ISSUE THREAD

**Issue by liuty10** [ChristophHaag/SteamVR-OpenHMD#9]
Hi, I am trying to find an Open Source VR game to play on Linux. Is Quake2VR for Linux an open source project? The original link seems invalid now. Do you have a new link to the game or other open source vr game for linux?

**Comment by TheOnlyJoey** [comment]
Ehh why is this posted in a SteamVR-OpenHMD project?
Not really relevant to the project..

Try the gamingonlinux forum or something like that.
